# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

services:
  - mysql

before_script:
  - echo "[toxboot]\nuser = travis-user\npassword = travis-pass\ndatabase = toxboot" | tee -a ~/.my.cnf
  - mysql -e 'create database toxboot;'
  - mysql -e "create user 'travis-user'@'localhost' identified by 'travis-pass';"

language: r
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jeroenooms/mongolite
  - jeroenooms/jsonlite

sudo: false
cache: packages


after_success:
  - Rscript -e 'covr::codecov()'
