# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

services:
  - mysql

before_script:
  - echo -e "[toxboot]\nuser = travis-user\npassword = travis-pass\ndatabase = toxboot" | cat > ~/.my.cnf
  - mysql -e 'create database toxboot;' -uroot
  - mysql -e "create user 'travis-user'@'localhost' identified by 'travis-pass';" -uroot
  - mysql -e "grant all privileges on toxboot.* to 'travis-user'@'localhost';" -uroot

language: r
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jeroenooms/mongolite
  - jeroenooms/jsonlite

sudo: false
cache: packages


after_success:
  - Rscript -e 'covr::codecov()'
