fitpars <- c("resp_max",
             "resp_min",
             "max_mean",
             "max_mean_conc",
             "max_med",
             "max_med_conc",
             "logc_max",
             "logc_min",
             "cnst",
             "hill",
             "hcov",
             "gnls",
             "gcov",
             "cnst_er",
             "cnst_aic",
             "cnst_rmse",
             "hill_tp",
             "hill_tp_sd",
             "hill_ga",
             "hill_ga_sd",
             "hill_gw",
             "hill_gw_sd",
             "hill_er",
             "hill_er_sd",
             "hill_aic",
             "hill_rmse",
             "gnls_tp",
             "gnls_tp_sd",
             "gnls_ga",
             "gnls_ga_sd",
             "gnls_gw",
             "gnls_gw_sd",
             "gnls_la",
             "gnls_la_sd",
             "gnls_lw",
             "gnls_lw_sd",
             "gnls_er",
             "gnls_er_sd",
             "gnls_aic",
             "gnls_rmse",
             "nconc",
             "npts",
             "nrep",
             "nmed_gtbl")

# The palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

documentation_vars <- c("_id",
                        "aeid",
                        "boot_type",
                        "spid",
                        "replicates",
                        "started",
                        "modified",
                        "git_commit",
                        "logc_vect",
                        "m3id_vect",
                        "resp_vect",
                        "conc_vect")
